services:
    food-details:
        image: "ghcr.io/nico-iaco/todo-springboot-3-benchmark:latest"
        container_name: todo-springboot-3-benchmark
        ports:
            - "11000:8080"
        environment:
            - TZ=Europe/Rome
        restart: unless-stopped
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory:  1G